import jsPDF from 'jspdf';

interface AnalysisData {
    summary: string;
    keywords: string[];
    sentiment: 'Positive' | 'Neutral' | 'Negative';
    confidence: number;
}

export const generatePDF = (fileName: string, data: AnalysisData) => {
    const doc = new jsPDF();

    // Title
    doc.setFontSize(20);
    doc.setTextColor(41, 128, 185); // Krishna Blue-ish
    doc.text("AI File Analysis Report", 20, 20);

    // File Name
    doc.setFontSize(12);
    doc.setTextColor(100);
    doc.text(`File: ${fileName}`, 20, 30);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 36);

    // Divider
    doc.setDrawColor(200);
    doc.line(20, 45, 190, 45);

    // Summary Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Summary", 20, 60);

    doc.setFontSize(11);
    doc.setTextColor(60);
    const splitSummary = doc.splitTextToSize(data.summary, 170);
    doc.text(splitSummary, 20, 70);

    let currentY = 70 + (splitSummary.length * 6) + 10;

    // Keywords Section
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Keywords", 20, currentY);

    doc.setFontSize(11);
    doc.setTextColor(60);
    doc.text(data.keywords.join(", "), 20, currentY + 10);

    currentY += 25;

    // Sentiment & Confidence
    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.text("Analysis Metrics", 20, currentY);

    doc.setFontSize(11);
    doc.setTextColor(60);
    doc.text(`Sentiment: ${data.sentiment}`, 20, currentY + 10);
    doc.text(`Confidence Score: ${(data.confidence * 100).toFixed(0)}%`, 20, currentY + 16);

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Generated by AI File Analyzer", 20, 280);

    // Save
    doc.save(`${fileName.split('.')[0]}_analysis.pdf`);
};
